### ISSUE TITLE
Questions about mysql on radosfs or CephFS or RBD

### ISSUE THREAD

**Issue by lh2debug** [y-trudeau/percona-server-rados#1]
Hi Trudeau,
Thanks for your presentation and implements for MySQL on Ceph. It helps me gather a better understanding of Ceph. And thank you for watching this issue while you are busy. I have serval questions.

Your MySQL is based on radosfs and radosfs is a non-posix distributed file system on Ceph. If we use CephFS which is a posix file system on Ceph, we can just change the data directory  of MySQL to CephFS to implement “MySQL on CephFS” without changing the codes of MySQL.
1. What is the difference of using CephFS or using radosfs ?

And we can just change the data directory of MySQL to Ceph RBD to implement “MySQL on Ceph RBD” (as you do on your presentation). And the performance of Ceph RBD is better than CephFS. 

2. What are the benefits of using rados rather than CephFS.

Thank you very much !!! I cannot figure out the quesitions myself, thanks!!!

**Comment by y-trudeau** [comment]
Hi, 
   I performed some tests on CephFS and found it is not atomic for
writes some cases.  Actually, from the CephFS documentation:

"If a client is writing to a file and fails, its writes are not
necessarily atomic. That is, the client may call write(2) on a file
opened with O_SYNC with an 8 MB buffer and then crash and the write may
be only partially applied. (Almost all file systems, even local file
systems, have this behavior.)"

Now, radosfs, the way it is designed, is atomic.  There are a few
things I would like to check with CephFS, there is way it could work.
My MySQL on Ceph isn't working right now, I just don't have the
bandwidth to investigate the issues and fix them.

Regards,

Yves

**Comment by lh2debug** [comment]
Thanks for your reply! It is very nice of you.
